# AutoMute Plugin Configuration
# Made by Boenyy

bannedWords:

# Default mute duration format:
# Examples: "10m" (10 minutes), "1h" (1 hour)
defaultDuration:

# Enable or disable logging to console
logEnabled: true
