name: AutoMute
version: 1.0.0
main: id.boenyy.automute.AutoMutePlugin
author: Boenyy
description: Automatically mute players who use banned words.
depend: [ AdvancedBan ]
api-version: 1.13
load: POSTWORLD

commands:
  automute:
    description: Manage banned words and auto-mute settings
    usage: /automute <subcommand>
    permission: automute.use
    permission-message: §cYou don't have permission to use this command.

permissions:
  automute.use:
    description: Allows use of /automute commands
    default: op
